### ISSUE TITLE
Do pNetwork v4 support xerc20 native tokens?

### ISSUE THREAD

**Issue by envin3** [pnetwork-association/pnetwork-v4#20]
https://github.com/pnetwork-association/pnetwork-v4/blame/c442ecef4683b29d75b6c52a8eb27b1b81dd21e3/solidity/src/Adapter.sol#L144

What happens if the native token is a xerc20?

**Comment by gitmp01** [comment]
Well in that case the adapter is misconfigured and the tokens would be transferred to the lockbox and be locked there until the owner moves them manually. This is assuming the lockbox is configured with the right pair.
