### ISSUE TITLE
Local chain instead of native chain

### ISSUE THREAD

**Issue by envin3** [pnetwork-association/pnetwork-v4#21]
https://github.com/pnetwork-association/pnetwork-v4/blob/c442ecef4683b29d75b6c52a8eb27b1b81dd21e3/solidity/src/Adapter.sol#L209

I would use native chain instead of local chain nomenclature.

**Comment by gitmp01** [comment]
Yeah, unfortunately if we use native it would make a conflict to what is used by the xERC20 jargon: for native they mean the native currency, not the native assets, hence why the new definition of local chain
