### ISSUE TITLE
Remove `EventBytes` struct and and emit `bytes` instead

### ISSUE THREAD

**Issue by gitmp01** [pnetwork-association/pnetwork-v4#43]
### Problem

Emit bytes [here](https://github.com/pnetwork-association/pnetwork-v4/blob/master/solidity/src/contracts/Adapter.sol#L214-L225) insteand of EventBytes

### Notes

Issues may arise with `memory` typed arrays, the `bytes.concat` can't work. In case, consider emitting the event by manually concatenating the data into a fixed size array

**Comment by TheMarvelFan** [comment]
@gitmp01 

It seems like this issue is untouched. 
I will be working on this now.

**Comment by gitmp01** [comment]
Hi @TheMarvelFan, 

this has already been handled by this PR #44

Thank you anyway
