### ISSUE TITLE
EOS `xerc20::mint` isn't working if the lockbox singleton is not set

### ISSUE THREAD

**Issue by gitmp01** [pnetwork-association/pnetwork-v4#46]
### Problem

[here](https://github.com/pnetwork-association/pnetwork-v4/blob/master/cpp/contracts/xerc20.token.cpp#L39)

```cpp
    lockbox_singleton _lockbox( get_self(), get_self().value );
    auto lockbox = _lockbox.get(); // <---- here
    bridges bridgestable( get_self(), get_self().value );
```

### Solution

Allow the mint action also when the lockbox is not set (on non-local chains)

**Comment by TheMarvelFan** [comment]
Hi @gitmp01 ,

I think we can solve this issue by checking whether the lockbox is set or not using the `_lockbox.exists()` method before assigning its value. 

If you like my solution, I can create a PR for this issue.

Thanks!

**Comment by gitmp01** [comment]
Hi @TheMarvelFan,
thanks for help, feel free to open a PR if you like.

Please note that we can't afford any remuneration for any other devs/volounteers work at the moment, but if that isn't what you are looking for here then we really appreciate any help the community can provide!

Now, on the problem above, we would like to be able to call mint, even when the lockbox does not exist, so it a matter of just using replacing the above line with the following:
```
auto lockbox = _lockbox.get_or_default(name(0));
```

Then everything should go smoothly :)

If you like to add a test for the token minting when the lockbox isn't set, you have my blessing ;)

**Comment by TheMarvelFan** [comment]
Hi @gitmp01 ,

I was about to make a PR today but it looks like someone else is already working on a fix for this.
I will look for another issue to contribute to, then.
