### ISSUE TITLE
Add action `setchainid` in order to set the local chain id in the contract 

### ISSUE THREAD

**Issue by gitmp01** [pnetwork-association/pnetwork-v4#47]
## Problem

EOS does not provide a way to acces the chain id from a contract. We need an action `setchainid` into the `adapter.hpp` in order to set it correctly (currently is set on Mainnet)

**Comment by envin3** [comment]
do we need this right now given we initially support only EOS and the chain id is hard wired?

**Comment by gitmp01** [comment]
Probably not, but it would make testing easier with Jungle Testnet
